# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  vmImage: ubuntu-latest

parameters: 
- name: environmentType
  type: string
  default: 'Sandbox'

- name: serviceConnectionName
  type: string
  default: 'DT Sandbox'

stages: 

  - stage: Deploy
    jobs:
    - deployment: Deploy
      environment: ${{parameters.environmentType}}
      strategy:
        runOnce:
          deploy:
            steps:
            - checkout: self
            - task: AzureCLI@2
              inputs:
                azureSubscription: ${{parameters.serviceConnectionName}}
                scriptType: 'bash'
                scriptLocation: 'inlineScript'
                inlineScript: |
                  az deployment sub create \
                    --name $(Build.BuildNumber) \
                    --location 'USGov Virginia'  \
                    --template-file 'Base Templates'/democode/main.bicep \
                    --parameters 'Base Templates'/democode/main.parameters.json